UPDATE activities SET long_description = '<p>Deep within the heart of the Gunung Mulu National Park lies an experience that defies all expectations. Our guided tours offer unparalleled access to pristine rainforests and colossal cave networks that have evolved over millions of years.</p><p>Prepared exclusively for travelers seeking an authentic adventure, this journey requires a reasonable level of fitness and a spirit of discovery. Our local Penan and Berawan guides are deeply knowledgeable about the local flora, fauna, and geology, ensuring that you return not just with stunning photographs, but with a profound understanding of this UNESCO World Heritage Site.</p>' WHERE id = 1;

UPDATE activities SET long_description = '<p>Suspended high above the rainforest floor, the Mulu Canopy Skywalk is one of the longest tree-based canopy walks in the world. Walking among the lush green foliage, you will be in the prime position to observe the vibrant birdlife, macaques, and fascinating insects that call the canopy their home.</p><p>This immersive ecological experience provides a totally different perspective of the rainforest. The walkway is securely built and suitable for most ages, though those with a fear of heights should proceed with caution. Early mornings offer the best chance to hear the chorus of the jungle awaking.</p>' WHERE id = 2;

UPDATE activities SET long_description = '<p>Follow the legendary route once taken by Kayan headhunters. The Headhunters Trail is a challenging but immensely rewarding trek that combines river journeys, jungle hiking, and a true test of endurance. You will travel by longboat up the Melinau River before trekking deep into the primary rainforest.</p><p>Along the way, experience the rich biodiversity of Sarawak. The trail passes through varying terrains, from peat swamp forests to steep ridges, concluding with a stay at Camp 5. It is a profound historical journey combined with breathtaking natural beauty.</p>' WHERE id = 3;

UPDATE activities SET long_description = '<p>Experience the serenity of the Melinau River under the blanket of dusk. As the sun sets, the rainforest undergoes a dramatic transformation. Nocturnal creatures awaken, and the sounds of the jungle shift into a different rhythm.</p><p>The highlight of this cruise is the spectacular bat exodus, where millions of bats spiral out of Deer Cave in search of food. Witnessing this natural phenomenon from the comfort of a traditional longboat, with the silhouette of the limestone pinnacles in the background, is an unforgettable experience.</p>' WHERE id = 4;


UPDATE accommodation SET long_description = '<p>Experience luxury amidst the wilderness. The Mulu Marriott Resort & Spa is a five-star oasis located just five minutes from the park headquarters. Built on wooden stilts over the Melinau River, the resort is connected by a series of wooden walkways that blend seamlessly with the natural environment.</p><p>Guests can enjoy world-class amenities including a large outdoor swimming pool, a Balinese-style spa, and exceptional dining at the Marriott Cafe. After a long day of trekking and cave exploration, return to plush bedding, air-conditioned comfort, and impeccable service.</p>' WHERE id = 1;

UPDATE accommodation SET long_description = '<p>Offering a perfect balance of comfort and accessibility, the Royal Mulu Resort (now under Marriott management in some sections) provides cozy mid-range chalets. Designed with traditional longhouse aesthetics, it allows guests to feel connected to the local culture while enjoying modern conveniences.</p><p>The resort features beautiful landscaped gardens, riverfront views, and is an excellent base for families and couples. It is a short walk or boat ride to the main park entrance, making early morning tours highly convenient.</p>' WHERE id = 2;

UPDATE accommodation SET long_description = '<p>For the budget-conscious traveler or backpacker, the Mulu National Park Hostel offers clean, comfortable, and highly affordable dormitory-style lodging. Located directly within the park headquarters, you cannot get any closer to the action.</p><p>The hostel fosters a communal atmosphere where travelers from all over the world share stories of their adventures. It includes access to shared bathrooms, a common kitchen area, and the nearby park cafeteria. It is the ideal choice for those whose priority is exploration over luxury.</p>' WHERE id = 3;

UPDATE accommodation SET long_description = '<p>Experience authentic Sarawakian hospitality at Benarat Inn. Located slightly outside the immediate park boundary, this quiet guesthouse offers a peaceful retreat away from the main tourist hubs. It is run by friendly locals who are eager to share their knowledge of the area.</p><p>The rooms are simple, clean, and provide everything you need for a restful night. Staying here also supports the local community directly. Transport to the park entrance can be easily arranged, and home-cooked local meals are often the highlight of the stay.</p>' WHERE id = 4;
