jdbc.url=jdbc:mysql://localhost:3306/tourism_db?useSSL=false&serverTimezone=Asia/Kuala_Lumpur&allowPublicKeyRetrieval=true
db.username=root
db.password=mulu2026
db.pool.maximum=10
db.pool.minimum=2
db.pool.timeout=30000
